version: '3.8'
services: 
    ecommerce_api:
        container_name: django_api
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on: 
            - ecommerce_db
        ports:
            - 8000:8000


    ecommerce_db:
        container_name: django_db
        image: postgres:latest
        restart: always
        environment: 
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        volumes:
            - .db_data:/var/lib/postgresql/data/
        
        

